ISSUE-967: Update Oracle Db Adapter to v4
phalcon/incubator-db pull request #1
Opened 2021-04-21 20:59 UTC by BeMySlaveDarlin

- [x] Removed:
    `Phalcon\Db\Adapter\Cacheable\Mysql`
    `Phalcon\Db\Adapter\Mongo\Client`
    `Phalcon\Db\Adapter\Mongo\Collection`
    `Phalcon\Db\Adapter\Mongo\Cursor`
    `Phalcon\Db\Adapter\Mongo\Db`
    `Phalcon\Db\Adapter\Mongo\DbRef`
    `Phalcon\Db\Adapter\Mongo\Document`
    `Phalcon\Db\Adapter\MongoDB\Exception`
    `Phalcon\Db\Adapter\MongoDB\GridFS`
    `Phalcon\Db\Adapter\MongoDB\Model`
    `Phalcon\Db\Adapter\MongoDB\Operation`
    `Phalcon\Db\Adapter\MongoDB\*`
    `Phalcon\Db\Adapter\Factory`
    `Phalcon\Db\Dialect\MysqlExtended`
    `Phalcon\Db\Result\Serializable`
- [x] Updated to v4:
    `Phalcon\Db\Adapter\Pdo\Oracle`
    `Phalcon\Db\Dialec\Oraclet`

2021-04-21 21:05 UTC, Jeckerson commented
Namespace must be `Phalcon\Incubator\Db` to respect repository name and also to not have collision with Phalcon itself.

2021-04-21 21:13 UTC, BeMySlaveDarlin commented
> Namespace must be `Phalcon\Incubator\Db` to respect repository name and also to not have collision with Phalcon itself.

Done

2021-04-22 22:33 UTC, Jeckerson requested changes

2021-04-22 22:33 UTC, Jeckerson commented on composer.json
> +      "Phalcon\\Db\\": "src/"
Fix namespace

2021-04-22 22:33 UTC, Jeckerson commented on composer.json
> +      "Phalcon\\Db\\Tests\\Unit\\": "tests/unit/"
Fix namespace

2021-04-22 22:33 UTC, Jeckerson commented on src/Adapter/Pdo/Oracle.php
> +        foreach ($this->fetchAll($sql, Enum::FETCH_NUM) as $field) {
Move outside cycle, it will execute every iteration.

2021-04-24 08:09 UTC, Jeckerson approved these changes

2021-04-24 08:09 UTC, merged